add test for multidatasample
marouaneamz/mmclassification pull request #6
Opened 2022-11-08 12:50 UTC by marouaneamz

#5

2022-11-09 10:32 UTC, marouaneamz commented
thank you for reviewing the test

2022-11-09 11:10 UTC, piercus requested changes

2022-11-09 11:10 UTC, piercus commented on tests/test_structures/test_datasample.py
> +        self._test_set_label(key='gt_label',data_sample=MultiTaskDataSample().to_cls_data_samples())
On my current understanding, here you are testing that you can set 
* a number
* a tensor number
* an array ....

like `multi_task_data_sample.set_get_label(number)`

I feel this is not what we want to achieve, please rework the whole unit test strategy

2022-11-09 11:10 UTC, piercus commented on tests/test_structures/test_datasample.py
> +        self.assertFalse(data_samples.get_task_mask('task2'),False)
Let's test first without any tasks as input like `MultiTaskDataSample()`

we could add the tasks optionnaly `MultiTaskDataSample(metainfo={
  'task0': {num_classes='10'},
  'task1': {}
})`


```suggestion
        data_sample = MultiTaskDataSample().set_gt_label(gt_label)
        self.assertTrue(data_sample.get_task_mask('task1'),True)
        self.assertTrue(data_sample.get_task_mask('task2'),False)
```

2022-11-09 11:10 UTC, piercus commented on tests/test_structures/test_datasample.py
> +class TestMultiTaskDataSample(GenericTest):
please add the following tests : 

### to_target_data_sample

* `data_sample.to_target_data_sample('ClsDataSample', 'task0')`
  * if gt_label['task0'] is a number with 'ClsDataSample' -> return a ClsDataSample
  * if gt_label['task0'] is a number bigger than 'num_data_sample' with 'ClsDataSample'  with MultiTaskDataSample(metainfo={ 'task0': {num_classes='10'}, 'task1': {} })-> throw an error
  * if gt_label['task0'] is a string -> throw an error
  * if 'task0' is not in gt_label -> throw an error
 
* `data_sample.to_target_data_sample('MultiTaskDataSample', 'nested_task')` -> return an other  'MultiTaskDataSample' with `get_gt_label` as expected
* `data_sample.to_target_data_sample('MultiTaskDataSample', 'nested_task')` throw an error if the gt_label for key `nested_task` is a number (and not a dictonnary)

2022-11-09 11:10 UTC, piercus commented on tests/test_structures/test_datasample.py
> +        self._test_set_label(key='gt_label',data_sample=MultiTaskDataSample().to_cls_data_samples())
you need to reimplement `_test_set_label` for `MultiTaskDataSample` and test the following polymorphism behavior : 

| Label set Input | metainfo | Expected get output |
|---|---|---|
| Dict | None | LabelData |
| Empty Dict | None | Empty LabelData |
| Dict with proper keys | metainfo | LabelData |
| Empty Dict | metainfo | Empty LabelData |
| Dict with outside keys | metainfo | Throw an error |

2022-11-09 16:53 UTC, piercus requested changes

2022-11-09 16:53 UTC, piercus commented on tests/test_structures/test_datasample.py
>          data_sample = ClsDataSample()
please checkout this part 

see https://stackoverflow.com/a/6963150

you should be able to do something like

```
git checkout -p my_multi_task_1_x-- tests/test_structures/test_datasample.py
```

2022-11-09 16:53 UTC, piercus commented on tests/test_structures/test_datasample.py
> +
move `data_sample2` init here

2022-11-09 16:53 UTC, piercus commented on tests/test_structures/test_datasample.py
> +        self.assertIsInstance(label, LabelData)
please test `label.getattr('task0') == 1`

2022-11-09 16:53 UTC, piercus commented on tests/test_structures/test_datasample.py
> +        self.assertIsInstance(label, LabelData)
please test `label.getattr('task0')` is raising an error

2022-11-09 16:53 UTC, piercus commented on tests/test_structures/test_datasample.py
> +        method({'task0': 0,'task1':2})
please use method2

2022-11-09 16:53 UTC, piercus commented on tests/test_structures/test_datasample.py
> +        method({})
method2

2022-11-09 16:53 UTC, piercus commented on tests/test_structures/test_datasample.py
> +        method({'task0': 0,'task3':2})
method2

2022-11-09 16:53 UTC, piercus commented on tests/test_structures/test_datasample.py
> +        method({'task0': 0,'task3':2})
method2 should fail here

2022-11-09 16:53 UTC, piercus commented on tests/test_structures/test_datasample.py
> +        self.assertIsInstance(label, LabelData)
Please test that `label.getattr('task0')` is not raising an error

2022-11-09 16:53 UTC, piercus commented on tests/test_structures/test_datasample.py
> +    def test_to_target_data_sample(self):
Good for me :-)

2022-11-10 13:11 UTC, marouaneamz commented
neglect the modifications on evaluation , it's just modifications to fix linter (I still can't pass the lint of mmlcs)

2022-11-14 09:25 UTC, piercus requested changes

2022-11-14 09:25 UTC, piercus commented on mmcls/structures/multi_task_data_sample.py
> +            self.pred_task.score = value
```suggestion
            self.pred_task = value
```

2022-11-14 09:25 UTC, piercus commented on mmcls/structures/multi_task_data_sample.py
> +            self.pred_task = LabelData(score=value)
```suggestion
            self.pred_task = LabelData(**value)
```

2022-11-14 09:25 UTC, piercus commented on mmcls/structures/multi_task_data_sample.py
> +        return task_name in self.gt_task.label
```suggestion
        return task_name in self.gt_task
```

2022-11-14 09:25 UTC, piercus commented on mmcls/structures/multi_task_data_sample.py
> +        label = self.gt_task.label[task_name]
```suggestion
        label = self.gt_task[task_name]
```

2022-11-14 09:25 UTC, piercus commented on mmcls/structures/multi_task_data_sample.py
> +        label = self.gt_task.label[task_name]
```suggestion
        label = self.gt_task[task_name]
```

2022-11-14 09:25 UTC, piercus commented on mmcls/structures/multi_task_data_sample.py
> +        label = self.gt_task.label[task_name]
```suggestion
        label = self.gt_task[task_name]
```

2022-11-14 09:25 UTC, piercus commented on mmcls/structures/multi_task_data_sample.py
> +        return label_task
please set also values from `self.pred_task[task_name]` into the output data_sample

2022-11-14 09:25 UTC, piercus commented on mmcls/structures/multi_task_data_sample.py
> +        label_task = MultiTaskDataSample().set_gt_task(value=label)
please set also values from `self.pred_task[task_name]` into the output data_sample

2022-11-14 09:25 UTC, piercus commented on tests/test_structures/test_datasample.py
> +        self.assertEqual(label.label['task0'], 0)
```suggestion
        self.assertEqual(label['task0'], 0)
```

2022-11-14 09:25 UTC, piercus commented on tests/test_structures/test_datasample.py
> +            label.label['task0']
```suggestion
            label['task0']
```

2022-11-14 09:25 UTC, piercus commented on tests/test_structures/test_datasample.py
> +            label.label['task0']
```suggestion
            label['task0']
```

2022-11-14 09:25 UTC, piercus commented on mmcls/structures/multi_task_data_sample.py
> +            self.gt_task.label = label.label
```suggestion
            self.gt_task = label
```

2022-11-14 09:25 UTC, piercus commented on tests/test_structures/test_datasample.py
> +    """
```suggestion
```

2022-11-14 12:56 UTC, piercus approved these changes

2022-11-14 13:42 UTC, merged